name: Build and Release

on:
  workflow_dispatch:
  push:
    paths:
      - '**.csproj'
      - 'Program.cs'
      - 'packages.lock.json'
      - 'icon.ico'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64] # [x64, x86]

    # env:

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # I will use this later
      # - name: Build
      #   run: dotnet build --configuration Release

      - name: Publish Single File Executable
        run: |
          bash if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            RID="linux-${{ matrix.arch }}"
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            RID="win-${{ matrix.arch }}"
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            RID="osx-${{ matrix.arch }}"
          fi
          echo "RID=$RID" >> $GITHUB_ENV
          dotnet publish -c Release -r $RID --self-contained true -p:PublishSingleFile=true

      - name: Set Executable Path
        run: |
          bash if [ "${{ matrix.os }}" == "windows-latest" ]; then
            FILE_PATH="bin/Release/net8.0/${{ env.RID }}/publish/extractor.exe"
          else
            FILE_PATH="bin/Release/net8.0/${{ env.RID }}/publish/extractor"
          fi
          echo "FILE_PATH=$FILE_PATH" >> $GITHUB_ENV

      - name: Upload Single File Executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: ${{ env.FILE_PATH }}

      - name: Show project directory tree
        run: |
          tree -f -a -I '.git'
