name: Build and Release

on:
  workflow_dispatch:
  push:
    paths:
      - '**.csproj'
      - 'Program.cs'
      - 'packages.lock.json'
      - 'icon.ico'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64] # [x64, x86]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      # - name: Build
      #   run: dotnet build --configuration Release --no-restore

      # - name: Test
      #   run: dotnet test --no-restore --verbosity normal

      # - name: Publish Normal
      #   run: dotnet publish --configuration Release --output ./publish

      - name: Publish single file executable
        run: dotnet publish --configuration Release -p:PublishSingleFile=true --output ./publish-standalone-${{ matrix.os }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Create Release Artifact
        run: |
          cd ./publish
          zip -r ../release.zip .
          cd ..
        continue-on-error: true

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-artifact
          path: release.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
