name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.csproj'
      - 'Program.cs'
      - 'icon.ico'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux-x64
          - os: windows-latest
            platform: win-x64
          - os: macos-latest
            platform: osx-x64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Get Project Version
        id: version
        run: echo ::set-output name=version::$(grep -oPm1 "(?<=<Version>)[^<]+" ./metadata-extractor-cli.csproj)

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Tag version
        run: git tag ${{ steps.version.outputs.version }}

      - name: Install dependencies
        run: dotnet restore

      - name: Publish Single File
        run: dotnet publish -c Release -p:PublishSingleFile=true -p:DebugType=none -p:PublishTrimmed=true -o ./publish/${{ matrix.os }}-${{ matrix.platform }}

      - name: Publish Single File without .NET Runtime
        run: dotnet publish -c Release -p:PublishSingleFile=true -p:SelfContained=false -p:DebugType=none -o ./publish/${{ matrix.os }}-${{ matrix.platform }}-no-runtime

      - name: Create Archives
        run: |
          mkdir archives
          cd ./publish/${{ matrix.os }}-${{ matrix.platform }}
          zip ../archives/extractor-${{ matrix.os }}-${{ matrix.platform }}.zip * 
          cd ../${{ matrix.os }}-${{ matrix.platform }}-no-runtime
          zip ../archives/extractor-${{ matrix.os }}-${{ matrix.platform }}-no-runtime.zip *
          cd ../..
        shell: bash

      - name: Upload Archives
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.platform }}
          path: ./archives/*.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Archives
        uses: actions/download-artifact@v4

      - name: List Archives
        run: ls -l ./archives
