name: Build and Release

on:
  workflow_dispatch:
  push:
    paths:
      - '**.csproj'
      - 'Program.cs'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      # When I finish this Workflow script, I will use the following matrix:
      # matrix:
      #   os: [ubuntu-latest, windows-latest, macos-latest]
      #   arch: [x64, x86]
      matrix:
        os: [ubuntu-latest]
        arch: [x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Show directory tree before upload artifacts
        run: |
          tree -f -a

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if: ${{ success() }}
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: bin/Release/net8.0/publish/**

      - name: Show directory tree after upload artifacts
        run: |
          tree -f -a
