name: Build and Release

on:
  workflow_dispatch:
  push:
    paths:
      - '**.csproj'
      - 'Program.cs'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      # When I finish this Workflow script, I will use the following matrix:
      # matrix:
      #   os: [ubuntu-latest, windows-latest, macos-latest]
      #   arch: [x64, x86]
      matrix:
        os: [ubuntu-latest, windows-latest]
        arch: [x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.204' # 8.0.0 might be enough. I just set it to the bersion I used.
          cache: true

      # Need to check if I need to install the dependencies or not
      # - name: Install dependencies
      #   run: dotnet add package MetadataExtractor --version 2.8.1

      # Do I need to restore the dependencies?
      # - name: Restore dependencies
      #   run: dotnet restore



