name: Build and Release

on:
  workflow_dispatch:
  push:
    paths:
      - '**.csproj'
      - 'Program.cs'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      # When I finish this Workflow script, I will use the following matrix:
      # matrix:
      #   os: [ubuntu-latest, windows-latest, macos-latest]
      #   arch: [x64, x86]
      matrix:
        os: [ubuntu-latest]
        arch: [x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Artifact
        run: |
          mkdir -p my-artifact
          echo "This is a sample artifact" > my-artifact/example.txt

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if: ${{ success() }}
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: bin/Release/net8.0/publish/** # Here I have problem with correct path

      - name: Show directory tree
        run: |
          tree -f -a -I '.git'

      - name: Show directory tree of workspace
        run: |
          tree -f -a -I '.git' ${{ github.workspace }}

      - name: Show directory structure of /home
        run: |
          tree -f -d -I '.git' /home
