name: Build and Release

on:
  workflow_dispatch:
  push:
    paths:
      - '**.csproj'
      - 'Program.cs'
      - 'packages.lock.json'
      - 'icon.ico'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64] # [x64, x86]

    env:
      CLI_NAME: 'extractor'

    steps:
      - uses: actions/checkout@v4

      - name: Set OS-specific environment variable
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            echo "OS_ENV=linux" >> $GITHUB_OUTPUT
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            echo "OS_ENV=windows" >> $GITHUB_OUTPUT  
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            echo "OS_ENV=macos" >> $GITHUB_OUTPUT
          fi

      - name: Print OS-specific environment variable
        run: |
          echo "$OS_ENV"

      # - name: Setup .NET
      #   uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: '8.0.x'

      # I will use this later
      # - name: Build
      #   run: dotnet build --configuration Release

      # - name: Publish Single File Executable
      #   run: dotnet publish -c Release -r ${{ matrix.os }}-${{ matrix.arch }} --self-contained true -p:PublishSingleFile=true

      # - name: Upload Single File Executable
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ matrix.os }}-${{ matrix.arch }}
      #     path: bin/Release/net8.0/${{ matrix.os }}-${{ matrix.arch }}/publish

      # - name: Show project directory tree
      #   run: |
      #     tree -f -a -I '.git'
