name: Build and Release

on:
  workflow_dispatch:
  push:
    paths:
      - '**.csproj'
      - 'Program.cs'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      # When I finish this Workflow script, I will use the following matrix:
      # matrix:
      #   os: [ubuntu-latest, windows-latest, macos-latest]
      #   arch: [x64, x86]
      matrix:
        os: [ubuntu-latest, windows-latest]
        arch: [x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.204' # 8.0.0 might be enough. I just set it to the version I used.

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if: ${{ success() }}
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: bin/Release/net8.0/publish/**

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          files: |
            **/*.exe
            **/*.dll
            **/*.json
            **/*.sh
            **/*.zip
            **/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.DYGNITORZ_SECRET }}
