name: Build and Release

on:
  workflow_dispatch:
  push:
    paths:
      - '**.csproj'
      - 'Program.cs'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64] # [x64, x86]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish Single File Executable
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            RID="linux-${{ matrix.arch }}"
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            RID="win-${{ matrix.arch }}"
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            RID="osx-${{ matrix.arch }}"
          fi
          echo "RID=$RID" >> $GITHUB_ENV
          dotnet publish -c Release -r $RID --self-contained true -p:PublishSingleFile=true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: .bin/Release/net8.0/${{ env.RID }}/publish/** # Here I have problem with correct path

      - name: Show project directory tree
        run: |
          tree -f -a -I '.git'

      - name: Show directory structure of /home/runner/work/
        run: |
          tree -f -I '.git' /home/runner/work/
